require_relative "word_definition.rb"
require_relative "new_word.rb"
require_relative "word_example.rb"
require_relative "synonym.rb"
require_relative "antonym.rb"
require_relative "full_dict.rb"
require_relative "word_game.rb"